backend:
  name: github
  repo: zuqiu2024/Firefly
  branch: main
  base_url: https://www.zhanxx81201.dpdns.org
  auth_endpoint: /api/auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布时间", name: "published", widget: "datetime" }
      - { label: "简介", name: "description", widget: "string" }
      - { label: "标签", name: "tags", widget: "list" }
      - { label: "分类", name: "category", widget: "string" }
      - { label: "草稿", name: "draft", widget: "boolean" }
      - { label: "封面图片", name: "image", widget: "string" }
      - { label: "正文", name: "body", widget: "markdown" }